### ISSUE TITLE
Post confessions only when more than 2 admins voted for approval.

### ISSUE THREAD

**Issue by zyml** [nusmodifications/nuswhispers#13]
One of the top few comments during STePS:

Since admin have differing opinions on what confessions should be posted on Facebook, why not only submit these confessions when at least 2 admins have voted for approval?

For example, Confession A:
+0 votes: pending
+1 votes: still pending
+2 votes: approved

The number of votes required should be configurable.

**Comment by yangshun** [comment]
I think we can close this now. Our current model works fine 😄
