### ISSUE TITLE
API Keys for submitting confessions.

### ISSUE THREAD

**Issue by zyml** [nusmodifications/nuswhispers#22]
Allow API keys to be used alongside with reCAPTCHA when a submit confession request is made.

This is extremely useful in allowing other developers to develop solutions (e.g. mobile apps, chat bots *cough*) using NUSWhispers API without the hindrance of the reCAPTCHA validation.

We can have an admin backend to create and revoke API keys.

**Comment by zyml** [comment]
Done and live in production :)

**Comment by yangshun** [comment]
Awesome! Do we have any testers? (:

**Comment by zyml** [comment]
Nope at the moment. Might be using it for myself for side projects but nothing set in stone yet.
