### ISSUE TITLE
Text duplication whenever a previous post is mentioned

### ISSUE THREAD

**Issue by calebchiam** [nusmodifications/nuswhispers#68]
If you cite a previous post e.g. by starting the post with #65432 and type a message, multiple highlights appear throughout the page, which can obstruct the checkboxes and submit button.

See images below for an illustration of this:
**Typing the post**
![capture31](https://user-images.githubusercontent.com/14286996/60955451-739f7380-a333-11e9-91a5-bd172580bed3.PNG)

**Highlighting the 'unseen' text**
![capture32](https://user-images.githubusercontent.com/14286996/60955455-7601cd80-a333-11e9-82ed-ddc43def18d8.PNG)

This is on Chrome.

**Comment by zyml** [comment]
Thanks for reporting the bug and my apologies for not fixing it soon enough. The fix is live. :)
